apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beszel-agent.fullname" . }}
  labels:
    {{- include "beszel-agent.labels" . | nindent 4 }}
type: Opaque
data:
  ssh-key: {{ .Values.env.KEY | b64enc | quote }}
  {{- if .Values.env.TOKEN }}
  token: {{ .Values.env.TOKEN | b64enc | quote }}
  {{- end }}
