blank_issues_enabled: false
contact_links:
  - name: ğŸ—£ï¸ Translations
    url: https://crowdin.com/project/beszel
    about: Please report translation issues and request new translations here. 
  - name: ğŸ’¬ Support and questions
    url: https://github.com/henrygd/beszel/discussions
    about: Ask and answer questions here.
  - name: â„¹ï¸ View the Common Issues page
    url: https://beszel.dev/guide/common-issues
    about: Find information about commonly encountered problems.
